import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LitLogo from '../components/LitLogo'
import HeaderLink from '../components/HeaderLink'
import BtnConnectWallet from '../components/BtnConnectWallet'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lit-Gather Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="relative h-screen h-10 mt-8 flex justify-between items-center">
        
        <div className="relative">
          <LitLogo></LitLogo> 
        </div>

        {/* Nav: Links */}
        <div className="flex items-center">
          <BtnConnectWallet></BtnConnectWallet>
        </div>
      </header>{/* ...Header */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
